### PR TITLE
authentication fixups, ETD embargo date check

### PR DESCRIPTION
**Pull request by jmartin-sul**
## Why was this change made? 🤔

this rebases my branch from #521 on @mjgiarlo's branch from #517, and rebases it all on current `main`.  some of my changes from #521 evaporate out.

happy to let #517 get merged, and then rebase this.

* typo fix
* slightly more modular prompting for username/password as needed (and if prompting for username, does so before browser launch)
* re-enables check for embargo date, with a bit more looser of a date expectation

a bit more detail in commit messages.

## Was README.md updated if necessary? 🤨

N/A, i think?

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jmartin-sul OK, got #517 merged. Thanks for your review! You're clear to rebase, and I will make time to review (and, if helpful, pair on) this today.

**Comment by jmartin-sul** [comment]
> @jmartin-sul OK, got #517 merged. Thanks for your review! You're clear to rebase. Can you ping me when you've done that? Then I'll make time to review (and, if helpful, pair on) this today.

@mjgiarlo np!  rebased and re-pushed.  happy to pair, no scheduled meetings besides standup.

**Comment by mjgiarlo** [comment]
I recommend that a few more of us do a multi-test run with this branch to confirm the authN changes work for us, including myself, @justinlittman, and @ndushay. I'll do so soon.

**Comment by mjgiarlo** [comment]
@jmartin-sul 💬 
> I recommend that a few more of us do a multi-test run with this branch to confirm the authN changes work for us, including myself, @justinlittman, and @ndushay. I'll do so soon.
> 
> For consistency, how about we test using:
> 
> ```shell
> $ bundle exec rspec spec/features/etd_creation_spec.rb spec/features/sdr_deposit_spec.rb
> ```

Unfortunately, I can't get any of the tests to pass now due to authN stuff. I'll see if I can toss up a commit (which we can test and possibly ditch or amend later).

**Comment by jmartin-sul** [comment]
> @jmartin-sul 💬
> 
> > I recommend that a few more of us do a multi-test run with this branch to confirm the authN changes work for us, including myself, @justinlittman, and @ndushay. I'll do so soon.
> > For consistency, how about we test using:
> > ```shell
> > $ bundle exec rspec spec/features/etd_creation_spec.rb spec/features/sdr_deposit_spec.rb
> > ```
> 
> Unfortunately, I can't get any of the tests to pass now due to authN stuff. I'll see if I can toss up a commit (which we can test and possibly ditch or amend later).

yikes, ok.  what sort of errors are you seeing?

**Comment by mjgiarlo** [comment]
@jmartin-sul 💬 
>
> yikes, ok. what sort of errors are you seeing?

This is what fixed me up: https://github.com/sul-dlss/infrastructure-integration-test/pull/522/commits/193a26660032b8d2bd6ae6d3b29b1e4a3a4bbe5e

**Comment by jmartin-sul** [comment]
> This is what fixed me up: [193a266](https://github.com/sul-dlss/infrastructure-integration-test/commit/193a26660032b8d2bd6ae6d3b29b1e4a3a4bbe5e)
> 
> @jmartin-sul @ndushay @justinlittman if y'all have time to pull the latest commits in this branch today and run `bundle exec rspec spec/features/etd_creation_spec.rb spec/features/sdr_deposit_spec.rb`, we may be close to a solution that works for all of us (🤞🏻).

worked for me!

**Comment by ndushay** [comment]
yay - it worked for me.

**Comment by lwrubel** [comment]
Just for kicks, I tested too and it worked for me, too. :)

**Comment by mjgiarlo** [comment]
Awesome, all! I'm going to merge this and will commit to working on a fix with @justinlittman if this doesn't work for his authN use case.

**Review by mjgiarlo — APPROVED** [review]

**Comment by justinlittman** [comment]
Hmmm ... just finished my testing:
```
rspec ./spec/features/virtual_object_creation_spec.rb:14 # Use Argo to create a virtual object with constituent objects is expected not to have css ".alert-danger" and {:wait=>0}
 1) Use Argo to create a virtual object with constituent objects is expected not to have css ".alert-danger" and {:wait=>0}
     Failure/Error: raise result[:output][:errors] if result[:output][:errors].present?
     
     TypeError:
       exception class/object expected
     # ./spec/support/deposit_helpers.rb:13:in `raise'
     # ./spec/support/deposit_helpers.rb:13:in `block (2 levels) in deposit'
     # ./spec/support/deposit_helpers.rb:11:in `loop'
     # ./spec/support/deposit_helpers.rb:11:in `block in deposit'
     # ./spec/support/deposit_helpers.rb:10:in `deposit'
     # ./spec/support/deposit_helpers.rb:39:in `deposit_object'
     # ./spec/features/virtual_object_creation_spec.rb:25:in `block (3 levels) in <top (required)>'
     # ./spec/features/virtual_object_creation_spec.rb:24:in `times'
     # ./spec/features/virtual_object_creation_spec.rb:24:in `block (2 levels) in <top (required)>'


rspec ./spec/features/sdr_deposit_spec.rb:12 # SDR deposit deposits objects
  1) SDR deposit deposits objects
     Failure/Error: raise result[:output][:errors] if result[:output][:errors].present?
     
     TypeError:
       exception class/object expected
     # ./spec/support/deposit_helpers.rb:13:in `raise'
     # ./spec/support/deposit_helpers.rb:13:in `block (2 levels) in deposit'
     # ./spec/support/deposit_helpers.rb:11:in `loop'
     # ./spec/support/deposit_helpers.rb:11:in `block in deposit'
     # ./spec/support/deposit_helpers.rb:10:in `deposit'
     # ./spec/features/sdr_deposit_spec.rb:14:in `block (2 levels) in <top (required)>'


rspec ./spec/features/etd_creation_spec.rb:72 # Create a new ETD with embargo, and then update the embargo date 

  1) Create a new ETD with embargo, and then update the embargo date 
     Failure/Error: raise "Error POSTing ETD: status #{resp.status}, #{resp.reason_phrase}, #{resp.body}"
     
     RuntimeError:
       Error POSTing ETD: status 401, Unauthorized, You are unauthorized to perform this action
     # ./spec/features/etd_creation_spec.rb:279:in `simulate_registrar_post'
     # ./spec/features/etd_creation_spec.rb:77:in `block (2 levels) in <top (required)>'

* This is a typical failure for me in QA.

rspec ./spec/features/web_archive_accessioning_spec.rb:39 # Use was-registrar-app, Argo, and pywb to ensure web archive crawl and seed accession is expected to have text "About us | Stanford Libraries"

Failures:

  1) Use was-registrar-app, Argo, and pywb to ensure web archive crawl and seed accession is expected to have text "About us | Stanford Libraries"
     Failure/Error: expect(page).to have_text('About us | Stanford Libraries')
       expected `#<Capybara::Session>.has_text?("About us | Stanford Libraries")` to be truthy, got false
     # ./spec/features/web_archive_accessioning_spec.rb:71:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 24.5 seconds (files took 2.45 seconds to load)
1 example, 1 failure
```

These were multiple consistent failures.

**Comment by mjgiarlo** [comment]
@justinlittman That ETD failure looks like what happens when the tests can't find legit ETD credentials in local settings, though it could of course be related to something else. Did you `mv config/settings/staging.local.yml config/settings/stage.local.yml` yet?

**Comment by mjgiarlo** [comment]
Those failures at least don't *look* like they're authn-related, but it'd sure be nice if the tests worked more reliably for each of us.

**Pull request merged**
