### PR TITLE
Use the new token GUI in Argo to get a token

### PR DESCRIPTION
**Pull request by jcoyne**
## Why was this change made?

So we don't need to log into SDR-API and create an account before running the tests.

## Was the usage documentation (e.g. README) updated?
n/a

### CODE REVIEW

**Comment by jermnelson** [comment]
All of the integration tests are failing (errors are below). Noticed one of the objects, https://argo-stage.stanford.edu/view/druid:bs743mp8478, has an error `descriptive-metadata : uninitialized constant Robots::DorRepo::Accession::DescriptiveMetadata::DruidTools Did you mean? UUIDTools` 

```
1) Use Argo to create an administrative policy object is expected to eq "adminPolicy"             
     Failure/Error: break if page.has_text?('v1 Accessioned')                                       
                                                                                                    
     Timeout::Error:                                                                                
       execution expired                                                                            
     # ./spec/features/create_apo_spec.rb:36:in `block (4 levels) in <top (required)>'              
     # ./spec/features/create_apo_spec.rb:34:in `loop'                                              
     # ./spec/features/create_apo_spec.rb:34:in `block (3 levels) in <top (required)>'              
     # ./spec/features/create_apo_spec.rb:33:in `block (2 levels) in <top (required)>' 

  2) Reaccession from preassembly is expected to text "Datastreams"
     Failure/Error: elem = find('dd.blacklight-status_ssi', text: 'Accessioned')
      
     Capybara::ElementNotFound:
       Unable to find visible css "dd.blacklight-status_ssi" with text "Accessioned"
     # ./spec/features/reaccession_via_preassembly_spec.rb:23:in `block (2 levels) in <top (required
)>'

3) SDR deposit deposits objects
     Got 0 failures and 2 other errors:

     3.1) Failure/Error: break if page.has_text?('v1 Accessioned')
           
          Timeout::Error:
            execution expired
          # ./spec/features/sdr_deposit_spec.rb:35:in `block (4 levels) in <top (required)>'
          # ./spec/features/sdr_deposit_spec.rb:33:in `loop'
          # ./spec/features/sdr_deposit_spec.rb:33:in `block (3 levels) in <top (required)>'
          # ./spec/features/sdr_deposit_spec.rb:32:in `block (2 levels) in <top (required)>'
 3.2) Failure/Error: Unable to find WebDriverError@chrome://marionette/content/error.js to read 
failed line
          Selenium::WebDriver::Error::NoSuchAlertError:
          # WebDriverError@chrome://marionette/content/error.js:175:5
          # NoSuchAlertError@chrome://marionette/content/error.js:376:5
          # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3376:11
          # GeckoDriver.prototype.dismissDialog@chrome://marionette/content/driver.js:3289:8
          # despatch@chrome://marionette/content/server.js:305:40
          # execute@chrome://marionette/content/server.js:275:16
          # onPacket/<@chrome://marionette/content/server.js:248:20
          # onPacket@chrome://marionette/content/server.js:249:9
          # _onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20

4) Use Argo to create a collection                                                       [79/1914]
     Got 0 failures and 2 other errors:

     4.1) Failure/Error: if page.has_content?('SUNet ID')
           
          NoMethodError:
            undefined method `map' for nil:NilClass
          # ./spec/support/authentication_helpers.rb:23:in `authenticate!'
          # ./spec/features/create_collection_spec.rb:14:in `block (2 levels) in <top (required)>'

     4.2) Failure/Error: Unable to find WebDriverError@chrome://marionette/content/error.js to read 
failed line
          Selenium::WebDriver::Error::NoSuchAlertError:
          # WebDriverError@chrome://marionette/content/error.js:175:5
          # NoSuchAlertError@chrome://marionette/content/error.js:376:5
          # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3376:
11
          # GeckoDriver.prototype.dismissDialog@chrome://marionette/content/driver.js:3289:8
          # despatch@chrome://marionette/content/server.js:305:40
          # execute@chrome://marionette/content/server.js:275:16
          # onPacket/<@chrome://marionette/content/server.js:248:20
          # onPacket@chrome://marionette/content/server.js:249:9
          # _onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20

 5) Use Argo to create an object without any files 
     Got 0 failures and 2 other errors:

     5.1) Failure/Error: if page.has_content?('SUNet ID')
           
          NoMethodError:
            undefined method `map' for nil:NilClass
          # ./spec/support/authentication_helpers.rb:23:in `authenticate!'
          # ./spec/features/create_object_no_files_spec.rb:13:in `block (2 levels) in <top (required
)>'

     5.2) Failure/Error: Unable to find WebDriverError@chrome://marionette/content/error.js to read 
failed line
          Selenium::WebDriver::Error::NoSuchAlertError:
          # WebDriverError@chrome://marionette/content/error.js:175:5
# NoSuchAlertError@chrome://marionette/content/error.js:376:5
          # GeckoDriver.prototype._checkIfAlertIsPresent@chrome://marionette/content/driver.js:3376:
11
          # GeckoDriver.prototype.dismissDialog@chrome://marionette/content/driver.js:3289:8
          # despatch@chrome://marionette/content/server.js:305:40
          # execute@chrome://marionette/content/server.js:275:16
          # onPacket/<@chrome://marionette/content/server.js:248:20
          # onPacket@chrome://marionette/content/server.js:249:9
          # _onJSONObjectReady/<@chrome://marionette/content/transport.js:501:20
```

**Comment by jcoyne** [comment]
@jermnelson are you seeing the same failure on master?

**Comment by jermnelson** [comment]
> @jermnelson are you seeing the same failure on master?

Yes, the same errors are being generated.

**Comment by jcoyne** [comment]
So, we can infer that problem has nothing to do with this PR.

**Comment by jcoyne** [comment]
@jermnelson I think this is the solution to the problem: https://github.com/sul-dlss/common-accessioning/pull/620

**Comment by jermnelson** [comment]
> @jermnelson I think this is the solution to the problem: [sul-dlss/common-accessioning#620](https://github.com/sul-dlss/common-accessioning/pull/620)

Cool, I approved and the merged this PR.

**Pull request merged**
